name: Update site every 15 minutes

on:
  schedule:
    - cron: '*/15 * * * *'  # ogni 15 minuti
  workflow_dispatch:       # consente anche avvio manuale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install requests beautifulsoup4
      - run: python main.py
      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "actions@github.com"
      - run: git add index.html
      - run: git commit -m "Auto-update $(date +'%Y-%m-%d %H:%M')" || echo "No changes"
      - run: git push
